### ISSUE TITLE
``print" in .md?

### ISSUE THREAD

**Issue by SherylHYX** [tczhangzhi/tczhangzhi#1]
Hi there,

I guess what you really want is a .py file if you want to use ``print", or just the text if you want to use .md. :)

**Comment by tczhangzhi** [comment]
It is just a python-style greeting message😂 because most computer vision researchers use python and believe _Talk is cheap and show me your code_, LOL. You can, of course, copy the code to a python script to run it, but it is a common way to use markdown to share codes. Please refer to some of my open-source projects' documents. BTW, u can set the language in markdown if u wish to highlight the keywords in your codes.
